# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=4.0.1
group=com.affehund.voidtotem
java_version=21
# Common
minecraft_version=1.21.11
mod_name=Void Totem
mod_author=Affehund
mod_id=voidtotem
license=GPL-3.0
credits=Thanks to all the translators, supporters, and helpers!
description=A totem that prevents you from dying in the void.
minecraft_version_range=[1.21.11]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# Fabric
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.5
trinkets_version=3.10.0
mod_menu_version=17.0.0
# NeoForge
neoforge_version=21.1.127
neoforge_loader_version_range=[4,)
curios_version=9.2.2+1.21.1
cloth_config_version=21.11.153
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
