modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory

license="GNU GPLv3"
issueTrackerURL="https://github.com/Affehund/VoidTotem/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/voidtotem" #optional
logoFile="logo.png" #optional
logoBlur=false
authors="Affehund" #optional
[[mods]] #mandatory
modId="voidtotem" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Void Totem" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Affehund/VoidTotem/master/update.json" #optional
description='''A mod that adds a totem that prevents you from dying in the void.'''